<testsuites name="results">
  <testsuite name="all" package="all">
    <property name="random_seed" value="1724501680" />
    <testcase name="run_test_read_001" classname="test_axil_register_wr" file="/Users/fatimafarooq/Desktop/axi_LLM/venv/lib/python3.12/site-packages/cocotb/regression.py" lineno="731" time="0.0036270618438720703" sim_time_ns="0.001" ratio_time="0.27570525208703084">
      <failure message="Test failed with RANDOM_SEED=1724501680" />
    </testcase>
    <testcase name="run_test_read_002" classname="test_axil_register_wr" file="/Users/fatimafarooq/Desktop/axi_LLM/venv/lib/python3.12/site-packages/cocotb/regression.py" lineno="731" time="0.018510818481445312" sim_time_ns="0.001" ratio_time="0.05402246264811953">
      <failure message="Test failed with RANDOM_SEED=1724501680" />
    </testcase>
    <testcase name="run_test_read_003" classname="test_axil_register_wr" file="/Users/fatimafarooq/Desktop/axi_LLM/venv/lib/python3.12/site-packages/cocotb/regression.py" lineno="731" time="0.0016202926635742188" sim_time_ns="0.001" ratio_time="0.6171724543849323">
      <failure message="Test failed with RANDOM_SEED=1724501680" />
    </testcase>
    <testcase name="run_test_read_004" classname="test_axil_register_wr" file="/Users/fatimafarooq/Desktop/axi_LLM/venv/lib/python3.12/site-packages/cocotb/regression.py" lineno="731" time="0.0016639232635498047" sim_time_ns="0.001" ratio_time="0.6009892534747099">
      <failure message="Test failed with RANDOM_SEED=1724501680" />
    </testcase>
  </testsuite>
</testsuites>
