<testsuites name="results">
  <testsuite name="all" package="all">
    <property name="random_seed" value="1724498875" />
    <testcase name="run_test_read_001" classname="test_axil_adapter_rd" file="/Users/fatimafarooq/Desktop/axi_LLM/venv/lib/python3.12/site-packages/cocotb/regression.py" lineno="731" time="0.006175994873046875" sim_time_ns="0.001" ratio_time="0.16191723285978998">
      <failure message="Test failed with RANDOM_SEED=1724498875" />
    </testcase>
    <testcase name="run_test_read_002" classname="test_axil_adapter_rd" file="/Users/fatimafarooq/Desktop/axi_LLM/venv/lib/python3.12/site-packages/cocotb/regression.py" lineno="731" time="0.0018248558044433594" sim_time_ns="0.001" ratio_time="0.5479885027436635">
      <failure message="Test failed with RANDOM_SEED=1724498875" />
    </testcase>
    <testcase name="run_test_read_003" classname="test_axil_adapter_rd" file="/Users/fatimafarooq/Desktop/axi_LLM/venv/lib/python3.12/site-packages/cocotb/regression.py" lineno="731" time="0.0017001628875732422" sim_time_ns="0.001" ratio_time="0.5881789370354789">
      <failure message="Test failed with RANDOM_SEED=1724498875" />
    </testcase>
    <testcase name="run_test_read_004" classname="test_axil_adapter_rd" file="/Users/fatimafarooq/Desktop/axi_LLM/venv/lib/python3.12/site-packages/cocotb/regression.py" lineno="731" time="0.0095062255859375" sim_time_ns="0.001" ratio_time="0.10519422150882825">
      <failure message="Test failed with RANDOM_SEED=1724498875" />
    </testcase>
  </testsuite>
</testsuites>
